# Generated by Django 5.0.6 on 2026-06-01 08:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, help_text='Current available stock. Never goes below 0 (DB constraint enforced).', validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved_quantity', models.IntegerField(default=0, help_text='Quantity reserved in pending orders.', validators=[django.core.validators.MinValueValidator(0)])),
                ('low_stock_threshold', models.IntegerField(default=5)),
                ('allow_backorder', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_record', to='catalog.product')),
            ],
            options={
                'db_table': 'inventory_stock_record',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase / Restock'), ('sale', 'Sale'), ('return', 'Return'), ('adjustment', 'Manual Adjustment'), ('reservation', 'Reservation'), ('reservation_release', 'Reservation Release'), ('reconcile', 'Reconciliation')], db_index=True, max_length=30)),
                ('quantity_delta', models.IntegerField(help_text='Positive = stock in, Negative = stock out')),
                ('quantity_before', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('reference', models.CharField(blank=True, help_text='Order ID, PO number, etc.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockrecord')),
            ],
            options={
                'db_table': 'inventory_stock_movement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='stockrecord',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 0)), name='stock_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stockrecord',
            constraint=models.CheckConstraint(check=models.Q(('reserved_quantity__gte', 0)), name='stock_reserved_non_negative'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['stock_record', '-created_at'], name='movement_record_date'),
        ),
    ]
