# Generated by Django 5.0.6 on 2026-06-01 08:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_type', models.CharField(choices=[('15min', '15 Minutes'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], db_index=True, max_length=10)),
                ('dimension', models.CharField(db_index=True, help_text='e.g. overall, category, vendor, product', max_length=50)),
                ('dimension_value', models.CharField(db_index=True, help_text='e.g. imaging, vendor-uuid, product-uuid, ALL', max_length=255)),
                ('metric', models.CharField(db_index=True, help_text='e.g. revenue, orders, units_sold, avg_order_value', max_length=50)),
                ('value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kpi_snapshot',
                'indexes': [models.Index(fields=['period_start', 'period_type', 'dimension', 'dimension_value'], name='kpi_snapshot_lookup')],
                'unique_together': {('period_start', 'period_type', 'dimension', 'dimension_value', 'metric')},
            },
        ),
    ]
