# Generated by Django 5.0.6 on 2026-06-01 08:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(db_index=True, max_length=254)),
                ('email_type', models.CharField(choices=[('welcome', 'Welcome'), ('order_confirmation', 'Order Confirmation'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('password_reset', 'Password Reset'), ('inquiry_received', 'Inquiry Received'), ('inquiry_reply', 'Inquiry Reply')], db_index=True, max_length=30)),
                ('reference_id', models.CharField(db_index=True, help_text='Order ID, User ID, or other entity ID this email relates to', max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('queued', 'Queued')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications_email_log',
                'indexes': [models.Index(fields=['recipient_email', 'email_type'], name='emaillog_recipient_type')],
                'unique_together': {('email_type', 'reference_id')},
            },
        ),
    ]
